version: '3.5'

services:
  eth-server:
    container_name: etherbeam_eth_server
    build: .
    environment:
      - NODE_ENV=production
      - NODE_PORT=3002
    volumes:
      - /var/log/etherbeam/eth-server:/app/log:rw
      - /etc/geth/geth.ipc:/app/geth/geth.ipc:ro
    networks:
      - etherbeam

networks:
  etherbeam:
    name: etherbeam-net
