version: '3.5'

services:
  eth-server:
    container_name: etherbeam_eth_server_dev
    build: .
    environment:
      - NODE_ENV=development
      - NODE_PORT=3002
    volumes:
      - ./log:/app/log:rw
    ports:
      - '3002:3000'
    networks:
      - etherbeam

networks:
  etherbeam:
    name: etherbeam-net
